name: cron

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - run: ./rand.sh
      - uses: stefanzweifel/git-auto-commit-action@v5
