name: cron

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run
        run: ./rand.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
