name: cron

on:
  workflow_dispatch:
  schedule:
    - cron: "20 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}
      - run: ./rand.sh
      - uses: stefanzweifel/git-auto-commit-action@v5
